import { cpSync, mkdirSync, copyFileSync, writeFileSync, existsSync, readFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { spawnSync } from 'node:child_process';
import { projectRoot } from '../lib/data-paths.js';
import { createSnapshot, removeChild } from '../lib/backups.js';
import { loadAccounts } from '../lib/config.js';

process.umask(0o077);
const name = `persona-vps-${new Date().toISOString().replace(/[:.]/g, '-')}`;
const output = join(projectRoot, 'dist'), stage = join(output, name);
mkdirSync(stage, { recursive: true, mode: 0o700 });
const entries = ['package.json', 'server.js', 'lib', 'public', 'scripts', 'deploy', 'test', 'support', 'Dockerfile', 'compose.yaml', '.env.example', '.dockerignore', '.gitattributes', '.gitignore', 'README.md', 'VPS.md', 'CHAT.md'];
for (const entry of entries) cpSync(join(projectRoot, entry), join(stage, entry), { recursive: true });
const snapshotRoot = join(stage, '.snapshot');
const snapshot = await createSnapshot({ outputDir: snapshotRoot });
mkdirSync(join(stage, 'data'), { mode: 0o700 });
copyFileSync(join(snapshot, 'bruno.sqlite'), join(stage, 'data', 'saldo.sqlite'));
copyFileSync(join(snapshot, 'ana.sqlite'), join(stage, 'data', 'saldo-ana.sqlite'));
const manifest = JSON.parse(readFileSync(join(snapshot, 'manifest.json'), 'utf8'));
manifest.files.bruno.name = 'data/saldo.sqlite'; manifest.files.ana.name = 'data/saldo-ana.sqlite';
writeFileSync(join(stage, 'dados-incluidos.json'), JSON.stringify(manifest, null, 2), { mode: 0o600, flush: true });
removeChild(stage, snapshotRoot);
mkdirSync(join(stage, 'secrets'), { mode: 0o700 });
const sourceAccounts = process.env.AUTH_ACCOUNTS_FILE || (existsSync(join(projectRoot, 'secrets', 'accounts.json')) ? join(projectRoot, 'secrets', 'accounts.json') : null);
writeFileSync(join(stage, 'secrets', 'accounts.json'), JSON.stringify(loadAccounts(sourceAccounts), null, 2), { mode: 0o600, flush: true });
const archive = resolve(output, `${name}.tar.gz`);
const result = spawnSync('tar', ['-czf', archive, '-C', output, name], { stdio: 'inherit' });
if (result.error || result.status !== 0) throw new Error(`Não foi possível compactar. A pasta preparada está em ${stage}.`);
console.log(`Pacote da VPS com os dois bancos: ${archive}`);
console.log('Os dados refletem este momento. Não publique esse pacote no GitHub.');
